---
- hosts: localhost
  gather_facts: false
  environment:
    # Clear the PYTHONPATH variable so that Ansible Tower doesn't
    # mix Python 2 modules with Python 3 modules (causes the enum
    # module to be of the wrong version and fail import of re).
    PYTHONPATH: ""
  vars:
    awx_url: "{{ lookup('env', 'TOWER_HOST') }}"
    awx_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    awx_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    awx_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') == '1' }}"
  tasks:
  - name: include Ansible Tower project definitions
    with_filetree: vars/projects
    when: >-
      item.state == 'file' and item.path != '.gitkeep'
    include_role:
      name: unimatrix-awx
    vars:
      awx_projects: "{{ lookup('file', item.src)|from_yaml_all|list }}"
